clean: true
objc: true
author: PAYCOMET
author_url: https://www.paycomet.com/
github_url: https://github.com/PAYCOMET/ios-bankstore
umbrella_header: PAYTPV/PAYTPV.h
framework_root: .
module: PAYTPV
sdk: iphonesimulator

